gitignore on workshop location because of cloned repository error in description
error: invalid path 'Workshops/while-in-use-location/'
error: Workshops/while-in-use-location/: cannot add to the index - missing --add option?
fatal: Unable to process path Workshops/while-in-use-location/